version: "3.8"

services:
  app:
    build:
      context: .
      target: ${ENV:-prod} # Usa 'prod' por defecto, puede ser 'dev' con ENV=dev
    ports:
      - "3000:80" # Mapea el puerto 80 del contenedor (nginx) al 3000 del host
    volumes:
      - .:/app
      - /app/node_modules # Evita montar node_modules en desarrollo
    environment:
      - NODE_ENV=${NODE_ENV:-production}
